@extends('layouts.app')
@section('title', 'Рідна Віра — Духовний центр')
@section('content')
<section class="hero"><div class="hero__shade"></div><div class="container site-container hero__content"><p>Духовний центр</p><h1>РІДНА ВІРА</h1><img src="{{ asset('assets/ornament.svg') }}" alt=""></div></section>
<section class="primary-links"><div class="container site-container"><div class="row g-3">
@foreach ([['Святині','sanctuary'],['Рідні Боги','gods'],['Обряди','rites'],['Слави','glory']] as [$title,$icon])
<div class="col-6 col-lg-3"><a class="primary-card" href="#"><svg><use href="{{ asset('assets/icons.svg') }}#{{ $icon }}"/></svg><strong>{{ $title }}</strong></a></div>
@endforeach
</div></div></section>
<section class="communities"><div class="communities__image"></div><div class="container site-container communities__inner"><div class="paper-card text-center"><h2>Громади та представництва</h2><div class="row g-4 text-start"><div class="col-md-6"><p>Духовний центр об’єднує громади Рідної Віри, духовних провідників та однодумців, які зберігають звичаї, обряди й світогляд наших Предків.</p></div><div class="col-md-6"><p>На порталі буде представлена карта громад, контакти представництв, календар подій та матеріали для тих, хто прагне долучитися до живої традиції.</p></div></div><div class="row g-3 mt-1">@foreach (['Полум’я Роду','Права','Росичі'] as $name)<div class="col-md-4"><a class="community-tile" href="#"><span>{{ $name }}</span></a></div>@endforeach</div><a class="btn btn-gold mt-4" href="#">Всі громади</a></div></div></section>
<section class="svarog" id="calendar"><div class="container site-container text-center"><h2>Коло Свароже</h2><div class="svarog__layout"><div class="svarog__side">@foreach ([['Велес','veles'],['Мокоша','mokosh'],['Коляда','kolyada'],['Перун','perun']] as [$name,$icon])<a class="deity-card" href="#"><svg><use href="{{ asset('assets/icons.svg') }}#{{ $icon }}"/></svg><strong>{{ $name }}</strong></a>@endforeach</div><img class="svarog__wheel" src="{{ asset('assets/wheel.svg') }}" alt="Коло Свароже"><div class="svarog__side">@foreach ([['Білобог','bilobog'],['Дажбог','dazhbog'],['Купайло','kupala'],['Всі свята','feasts']] as [$name,$icon])<a class="deity-card" href="#"><svg><use href="{{ asset('assets/icons.svg') }}#{{ $icon }}"/></svg><strong>{{ $name }}</strong></a>@endforeach</div></div><a class="btn btn-gold mt-3" href="#">Всі свята</a></div></section>
@foreach (['Новини','Статті','Творчість'] as $section)
<section class="content-section"><div class="container site-container"><h2>{{ $section }}</h2><div class="row g-4"><div class="col-lg-7"><a class="featured-story" href="#"><img src="{{ asset('assets/article.svg') }}" alt="Світолад української оселі"><div class="featured-story__shade"></div><div class="featured-story__content"><span class="date-pill">20.03.2027</span><h3>Світолад української оселі</h3><p>Духовна спадщина, звичаї та символіка українського дому.</p><b>→</b></div></a></div><div class="col-lg-5"><div class="story-list">@for ($i=0;$i<3;$i++)<a class="story-item" href="#"><img src="{{ asset('assets/article.svg') }}" alt=""><span><strong>Структура замовляння у слов’ян</strong><small>20.03.2027</small></span></a>@endfor</div></div></div></div></section>
@endforeach
@endsection
