<?php

return [
    'source' => 'https://svit.in.ua/kny/Pashnyk.htm',
    'books' => [
        [
            'title' => 'Рідна Віра у питаннях і відповідях',
            'author' => 'Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 76,
            'category' => 'Основи віри',
            'cover' => 'https://svit.in.ua/kramn/kn/pytan.jpg',
            'description' => 'Відповіді на найчастіші питання про Рідну Віру, громаду, світогляд, обряди, календар та словник Руських Богів.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_vidpovidi.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_vidpovidi.docx',
            ],
        ],
        [
            'title' => 'Велесова Книга',
            'author' => 'Переклад і коментарі С.Д. Пашника',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 192,
            'category' => 'Духовні джерела',
            'cover' => 'https://svit.in.ua/kramn/kn/vk.jpg',
            'description' => 'Духовні тексти давньої Русі з перекладом, коментарями, словником та ілюстраціями для уважного читання джерела.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_vel_kn.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_vel_kn.docx',
            ],
        ],
        [
            'title' => 'Рідні Боги',
            'author' => 'Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 136,
            'category' => 'Боги',
            'cover' => 'https://svit.in.ua/kny/pashnyk/bogy.jpg',
            'description' => 'Збірник дослідницьких статей про Рідних Богів, їхні образи, природні прояви та місце у молитвах і світогляді.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_bogy.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_bogy.docx',
            ],
        ],
        [
            'title' => 'Руський Православний Календар',
            'author' => 'Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 216,
            'category' => 'Календар',
            'cover' => 'https://svit.in.ua/kramn/kn/kalen.jpg',
            'description' => 'Праця про календар свят, обчислення дат, Коло Свароже, астрономічні точки та етнокультурні основи річного кола.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kalendar.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kalendar.docx',
            ],
        ],
        [
            'title' => 'Іменослов',
            'author' => 'Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 76,
            'category' => 'Звичай',
            'cover' => 'https://svit.in.ua/kramn/kn/imena.jpg',
            'description' => 'Порадник для добору імені з поясненнями значень, прикладами давніх імен та їхнім духовним змістом.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_imenoslov.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_imenoslov.docx',
            ],
        ],
        [
            'title' => 'Біблійна мітологія',
            'author' => 'Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 104,
            'category' => 'Дослідження',
            'cover' => 'https://svit.in.ua/kny/pashnyk/bibl.jpg',
            'description' => 'Розгляд біблійних сюжетів через мітологічні паралелі та давні образи, що передували пізнішим релігійним текстам.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_bibl.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_bibl.docx',
            ],
        ],
        [
            'title' => 'Мітологічні таїни літописів',
            'author' => 'Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 88,
            'category' => 'Дослідження',
            'cover' => 'https://svit.in.ua/kny/pashnyk/litopys_obk.jpg',
            'description' => 'Дослідження мітологічних мотивів у літописах, де стародавні сюжети могли ставати частиною історичного письма.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_litopys.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_litopys.docx',
            ],
        ],
        [
            'title' => 'Бойовий дух воїна',
            'author' => 'Упорядник Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 60,
            'category' => 'Воїнський дух',
            'cover' => 'https://svit.in.ua/kramn/kn/duh.jpg',
            'description' => 'Матеріали для гартування духу захисника Русі-України, патріотичного виховання і духовного зміцнення воїна.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_duh.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_duh.docx',
            ],
        ],
        [
            'title' => 'Священний острів Хортиця',
            'author' => 'Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 112,
            'category' => 'Святині',
            'cover' => 'https://svit.in.ua/kramn/kn/hort.jpg',
            'description' => 'Статті про Хортицю, археологічні дослідження, світогляд Предків і мітологічне осмислення священного острова.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_hortycia.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_hortycia.docx',
            ],
        ],
        [
            'title' => 'Молитовник',
            'author' => 'Упорядник С.Д. Пашник',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 92,
            'category' => 'Молитви',
            'cover' => 'https://svit.in.ua/kramn/kn/molyt.jpg',
            'description' => 'Молитви, замовляння і промовки для свят, обрядів, лікування та щоденного духовного життя рідновіра.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_molytovnyk.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_molytovnyk.docx',
            ],
        ],
        [
            'title' => 'Пісенник',
            'author' => 'Упорядник С.Д. Пашник',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 60,
            'category' => 'Пісні',
            'cover' => 'https://svit.in.ua/kramn/kn/pisni.jpg',
            'description' => 'Добірка пісень, рекомендованих для виконання під час обрядів та свят Рідної Віри.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_pisennyk.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_pisennyk.docx',
            ],
        ],
        [
            'title' => 'Триглав',
            'author' => 'Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 44,
            'category' => 'Символіка',
            'cover' => 'https://svit.in.ua/kny/pashnyk/tryglav_obk.jpg',
            'description' => 'Дослідження священного символу Триглава-Тризуба, його мітологічних, державних і світоглядних значень.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_tryglav.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_tryglav.docx',
            ],
        ],
        [
            'title' => 'Рідна Віра для дітей',
            'author' => 'Упорядник С.Д. Пашник',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 40,
            'category' => 'Для дітей',
            'cover' => 'https://svit.in.ua/kny/pashnyk/dytyna_obk.jpg',
            'description' => 'Твори для дітей про чарівний світ Природи, Рідних Богів, священність України та бережне ставлення до життя.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_dytyna.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_dytyna.docx',
            ],
        ],
        [
            'title' => 'Великдень',
            'author' => 'Уклав Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 20,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/vekykden.jpg',
            'description' => 'Обряд і пояснення Великодня як весняного сонячного свята, пов’язаного з рівноденням, Ярилом і відродженням природи.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_velykden.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_velykden.docx',
            ],
        ],
        [
            'title' => 'Купало',
            'author' => 'Уклав Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 40,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/kup_obk.jpg',
            'description' => 'Матеріал про Купала, літній сонцеворот, очищення водою й вогнем, молодіжні дійства та зустріч Сонця-Купали.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kupalo.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kupalo.docx',
            ],
        ],
        [
            'title' => 'Славлення Перуна',
            'author' => 'Уклав Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 28,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/perun_obk.jpg',
            'description' => 'Обряд вечірнього славлення Перуна, воїнські змагання, присяга на вірність Вітчизні та дубові вінки сили.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_perun.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_perun.docx',
            ],
        ],
        [
            'title' => 'Симаргл',
            'author' => 'Уклав Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 16,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/sym-obk.jpg',
            'description' => 'Свято Вогню Симаргла, поновлення хатнього вогню, осінній перехід і символіка земного тепла.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_symargl.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_symargl.docx',
            ],
        ],
        [
            'title' => 'Колодій',
            'author' => 'Уклав Пашник С.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 28,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/kolodii.jpg',
            'description' => 'Зимове свято Колодія, його шестиденний цикл, похорон Колодки і роль Велеса як провідника потойбіччя.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kolodii.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kolodii.docx',
            ],
        ],
        [
            'title' => 'Калита',
            'author' => 'Уклав С.Д. Пашник',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 20,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/kalyta_obk.jpg',
            'description' => 'Молодіжне осіннє свято з ворожінням на долю, випробуваннями, весільною символікою і народними розвагами.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kalyta.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kalyta.docx',
            ],
        ],
        [
            'title' => 'Посвячення у рідновіри',
            'author' => 'Уклав Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 20,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/posviata_obk.jpg',
            'description' => 'Обряд приєднання людини до Роду Земного, зв’язку з Предками, Рідною Землею та відповідальності перед Родом.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_posviata.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_posviata.docx',
            ],
        ],
        [
            'title' => 'Вінчання',
            'author' => 'Уклали С.Д. Пашник, Я.В. Яковенко',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 44,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/vin_obk.jpg',
            'description' => 'Обряд створення родини зі збереженням основних звичаєвих рис, поясненням символічних дій і місцевих відмінностей.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_vinchannia.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_vinchannia.docx',
            ],
        ],
        [
            'title' => 'Поховання',
            'author' => 'Уклав С.Д. Пашник',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 28,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/poh_obk.jpg',
            'description' => 'Сучасний обряд поховання, укладений на основі стародавніх звичаїв і світогляду українського народу.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_pohovannia.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_pohovannia.docx',
            ],
        ],
        [
            'title' => 'Богославлення',
            'author' => 'Уклав Пашник С.Д.',
            'publisher' => 'Запоріжжя: Рідна Віра',
            'year' => '7534 (2026)',
            'pages' => 20,
            'category' => 'Обряди',
            'cover' => 'https://svit.in.ua/kny/pashnyk/bogos.jpg',
            'description' => 'Загальний обряд Богославлення для громади, побудований на прикладі хортицького святилища-обсерваторії.',
            'formats' => [
                'pdf' => 'https://svit.in.ua/kny/pashnyk/pashnyk_bogoslav.pdf',
                'docx' => 'https://svit.in.ua/kny/pashnyk/pashnyk_bogoslav.docx',
            ],
        ],
    ],
];
