<?php

return [
    'source' => 'https://www.svit.in.ua/bog.htm',
    'gods' => [
        ['slug' => 'bilobog', 'title' => 'Білобог', 'source_url' => 'https://www.svit.in.ua/bogy/bil_chor.htm', 'motif' => 'sun'],
        ['slug' => 'bog', 'title' => 'Бог', 'source_url' => 'https://svit.in.ua/kny/pashnyk/pashnyk_bogy.pdf', 'motif' => 'world'],
        ['slug' => 'veles', 'title' => 'Велес', 'source_url' => 'https://www.svit.in.ua/bogy/veles.htm', 'motif' => 'horns'],
        ['slug' => 'viy', 'title' => 'Вій', 'source_url' => 'https://www.svit.in.ua/pra/2p8.htm', 'motif' => 'eye'],
        ['slug' => 'goryn', 'title' => 'Горинь', 'source_url' => 'https://www.svit.in.ua/bogy/goryn.htm', 'motif' => 'mountain'],
        ['slug' => 'dazhbog', 'title' => 'Дажбог', 'source_url' => 'https://www.svit.in.ua/bogy/dazhbog.htm', 'motif' => 'sun-rider'],
        ['slug' => 'dana', 'title' => 'Дана', 'source_url' => 'https://www.svit.in.ua/bogy/dana.htm', 'motif' => 'water'],
        ['slug' => 'dyv', 'title' => 'Див', 'source_url' => 'https://www.svit.in.ua/bogy/dyv.htm', 'motif' => 'bird'],
        ['slug' => 'dolia', 'title' => 'Доля', 'source_url' => 'https://www.svit.in.ua/pra/11p4.htm', 'motif' => 'thread'],
        ['slug' => 'zhalia', 'title' => 'Жаля', 'source_url' => 'https://www.svit.in.ua/bogy/zhalia.htm', 'motif' => 'tear'],
        ['slug' => 'karyna', 'title' => 'Карина', 'source_url' => 'https://www.svit.in.ua/bogy/karyna.htm', 'motif' => 'flame-tear'],
        ['slug' => 'koliada', 'title' => 'Коляда', 'source_url' => 'https://www.svit.in.ua/bogy/koliada.htm', 'motif' => 'star'],
        ['slug' => 'kupalo', 'title' => 'Купало', 'source_url' => 'https://www.svit.in.ua/bogy/kupalo.htm', 'motif' => 'fire-water'],
        ['slug' => 'lad', 'title' => 'Лад', 'source_url' => 'https://svit.in.ua/pra/9p4.htm', 'motif' => 'wreath'],
        ['slug' => 'lada', 'title' => 'Лада', 'source_url' => 'https://svit.in.ua/pra/3p2.htm', 'motif' => 'wreath'],
        ['slug' => 'mamai', 'title' => 'Мамай', 'source_url' => 'https://www.svit.in.ua/stat/st91.htm', 'motif' => 'sun-horse'],
        ['slug' => 'mara', 'title' => 'Мара', 'source_url' => 'https://svit.in.ua/pra/9p2.htm', 'motif' => 'winter'],
        ['slug' => 'marena', 'title' => 'Марена', 'source_url' => 'https://svit.in.ua/kny/pashnyk/pashnyk_kupalo.pdf', 'motif' => 'winter'],
        ['slug' => 'matyr-sva', 'title' => 'Матир-сва', 'source_url' => 'https://www.svit.in.ua/stat/st48.htm', 'motif' => 'bird'],
        ['slug' => 'myrobog', 'title' => 'Миробог', 'source_url' => 'https://www.svit.in.ua/bogy/myr.htm', 'motif' => 'horizon'],
        ['slug' => 'mokosh', 'title' => 'Мокош', 'source_url' => 'https://www.svit.in.ua/bogy/mokosh.htm', 'motif' => 'loom'],
        ['slug' => 'moroz', 'title' => 'Мороз', 'source_url' => 'https://svit.in.ua/pra/12p2.htm', 'motif' => 'snow'],
        ['slug' => 'obida', 'title' => 'Обіда', 'source_url' => 'https://www.svit.in.ua/bogy/obida.htm', 'motif' => 'thorn'],
        ['slug' => 'perun', 'title' => 'Перун', 'source_url' => 'https://www.svit.in.ua/bogy/perun.htm', 'motif' => 'thunder'],
        ['slug' => 'porevyt', 'title' => 'Поревит', 'source_url' => 'https://svit.in.ua/stat/st65.htm', 'motif' => 'pillar'],
        ['slug' => 'porenut', 'title' => 'Поренут', 'source_url' => 'https://svit.in.ua/stat/st65.htm', 'motif' => 'pillar'],
        ['slug' => 'radogost', 'title' => 'Радогост', 'source_url' => 'https://svit.in.ua/pra/9p4.htm', 'motif' => 'wreath'],
        ['slug' => 'rod', 'title' => 'Род', 'source_url' => 'https://www.svit.in.ua/stat/st86.htm', 'motif' => 'world-tree'],
        ['slug' => 'rozhanytsia', 'title' => 'Рожаниця', 'source_url' => 'https://www.svit.in.ua/stat/st86.htm', 'motif' => 'cradle'],
        ['slug' => 'ruevyt', 'title' => 'Руєвит', 'source_url' => 'https://www.svit.in.ua/bogy/kupalo.htm', 'motif' => 'pillar'],
        ['slug' => 'rusalka', 'title' => 'Русалка', 'source_url' => 'https://svit.in.ua/pra/5p4.htm', 'motif' => 'water'],
        ['slug' => 'svarog', 'title' => 'Сварог', 'source_url' => 'https://svit.in.ua/stat/st86.htm', 'motif' => 'forge'],
        ['slug' => 'sviatovyt', 'title' => 'Святовит', 'source_url' => 'https://www.svit.in.ua/bogy/dazhbog.htm', 'motif' => 'pillar'],
        ['slug' => 'symargl', 'title' => 'Симаргл', 'source_url' => 'https://www.svit.in.ua/bogy/symargl.htm', 'motif' => 'winged-fire'],
        ['slug' => 'strybog', 'title' => 'Стрибог', 'source_url' => 'https://www.svit.in.ua/bogy/strybog.htm', 'motif' => 'wind'],
        ['slug' => 'khors', 'title' => 'Хорс', 'source_url' => 'https://svit.in.ua/stat/st28.htm', 'motif' => 'solar-horse'],
        ['slug' => 'chyslobog', 'title' => 'Числобог', 'source_url' => 'https://www.svit.in.ua/bogy/chyslo.htm', 'motif' => 'calendar'],
        ['slug' => 'chornobog', 'title' => 'Чорнобог', 'source_url' => 'https://www.svit.in.ua/bogy/bil_chor.htm', 'motif' => 'moon'],
        ['slug' => 'yama', 'title' => 'Яма', 'source_url' => 'https://www.svit.in.ua/bogy/yama.htm', 'motif' => 'gate'],
        ['slug' => 'yarylo', 'title' => 'Ярило', 'source_url' => 'https://www.svit.in.ua/bogy/yarylo.htm', 'motif' => 'sprout-sun'],
        ['slug' => 'yarovyt', 'title' => 'Яровит', 'source_url' => 'https://www.svit.in.ua/bogy/yarylo.htm', 'motif' => 'spear-sun'],
        ['slug' => 'yasna', 'title' => 'Ясна', 'source_url' => 'https://www.svit.in.ua/bogy/yasna.htm', 'motif' => 'dawn-star'],
    ],
];
